# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode11.1
language: swift
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
- set -o pipefail
- xcodebuild build -workspace Example/comthreadsafety.xcworkspace -sdk iphonesimulator -scheme comthreadsafety-Example -configuration Debug -destination "platform=iOS Simulator,name=iPhone 8" -destination "platform=iOS Simulator,name=iPhone 8 Plus" | xcpretty -c
- pod lib lint
