# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode11.1
language: swift
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
- xctool -workspace Example/comthreadsafety.xcworkspace -scheme comthreadsafety-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
- xctool test -workspace Example/comthreadsafety.xcworkspace -scheme comthreadsafety-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
- pod lib lint
